version: '3.9'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 8088:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tehnohem
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mg.com
      PGADMIN_DEFAULT_PASSWORD: admin